[
    {
        "leagueId": "ba2ae51d-f7e6-4165-9545-546611de7001",
        "queueType": "RANKED_FLEX_SR",
        "tier": "SILVER",
        "rank": "III",
        "summonerId": "DL4iqENv3Nmkp5lEHiCx-6YPXIjG39vv-fdjGaYs2CoN0Q",
        "summonerName": "derpyhead999",
        "leaguePoints": 0,
        "wins": 30,
        "losses": 27,
        "veteran": False,
        "inactive": False,
        "freshBlood": False,
        "hotStreak": False,
    },
    {
        "leagueId": "91ce025f-f176-44f0-a7ab-0406d4721b59",
        "queueType": "RANKED_SOLO_5x5",
        "tier": "SILVER",
        "rank": "III",
        "summonerId": "DL4iqENv3Nmkp5lEHiCx-6YPXIjG39vv-fdjGaYs2CoN0Q",
        "summonerName": "derpyhead999",
        "leaguePoints": 75,
        "wins": 32,
        "losses": 25,
        "veteran": False,
        "inactive": False,
        "freshBlood": False,
        "hotStreak": False,
    },
]
